program: credipred/experiments/gnn_experiments/sweep_train.py
method: bayes
metric:
  name: val/loss
  goal: minimize

parameters:
  # Fixed parameters
  config_file:
    value: "configs/gnn/gat_domainrel.yaml"
  model:
    value: "GAT"

  # Hyperparameters to sweep
  num_layers:
    values: [2, 3, 4]
  hidden_channels:
    values: [128, 256, 512]
  dropout:
    distribution: uniform
    min: 0.0
    max: 0.5
  lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
  weight_decay:
    distribution: log_uniform_values
    min: 0.00001
    max: 0.01
  batch_size:
    values: [512, 1024, 2048]

early_terminate:
  type: hyperband
  min_iter: 10
  eta: 3
